### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by harikt** [grangier/python-goose#138]
Hi, 

Is there a way we can set a timeout for the Goose when fetching and processing the article. Some are waiting quite some time.

May be the server is not properly responding.

**Comment by mpkuse** [comment]
I am wondering how to use it in practice? I have something like:

```
url = 'http://eng.belta.by/society/view/belarusian-buyers-of-geely-cars-promised-subsidies-107864-2017/'
g = Goose()
article = g.extract( url=url )

print article.title
```
