### ISSUE TITLE
Could not extract a Chinese html

### ISSUE THREAD

**Issue by yetuweiba** [grangier/python-goose#155]
Hello.Thanks for your python-goose. When I test python-goose,find a problem.
the codes are as follows:

from goose import Goose
from goose.text import StopWordsChinese
url = 'http://www.chinanews.com/gj/2014/11-19/6791729.shtml'
g = Goose({'stipwords_class':StopWordsChinese})
article = g.extract(url = url)
print article.cleaned_text[:150]

and the print is null.

**Comment by adangadang** [comment]
Goose({'stopwords_class': StopWordsChinese})
