### ISSUE TITLE
Why can't Goose extract these Chinese articles?

### ISSUE THREAD

**Issue by motasay** [grangier/python-goose#233]
Example article: http://tech.hexun.com.tw/2009-06-22/118866465.html

Note that the issue is present with this whole website.

I have set the stop word class, the target language, every other param that I thought was needed to be set explicitly, but without luck in getting the text using Goose.

What's causing Goose to not be able to extract the articles from this website?

Thanks,

**Comment by muggot** [comment]
The possible cause - charset gb2312, but decoding of page to unicode in python is failed

**Comment by muggot** [comment]
Valid codec for this site is 'gbk'. So the problem is in site settings.
If I use 'gbk' to decode text then all is ok at least in my branch.

**Comment by motasay** [comment]
Thanks @muggot, but how do I set the codec?

**Comment by muggot** [comment]
Eg.

```
import urllib2
import goose

f = urllib2.urlopen("http://tech.hexun.com.tw/2009-06-22/118866465.html")
raw_html = f.read()
g = goose.Goose()
a = g.extract(raw_html=unicode(raw_html,"gbk"))
print repr(a.cleaned_text)
```

**Comment by motasay** [comment]
Ah, forgot that goose can take the raw HTML! Thanks a lot @muggot !

**Comment by motasay** [comment]
Sorry about that, so here's the full snippet that will extract the text:

```
import urllib2
import goose
from goose.text import StopWordsChinese

goose_configs = {
    'enable_image_fetching': False,
    'use_meta_language':False,
    'target_language': 'zh',
    'stopwords_class': StopWordsChinese
}

f = urllib2.urlopen("http://tech.hexun.com.tw/2009-06-22/118866465.html")
raw_html = f.read()
g = goose.Goose(goose_configs)
a = g.extract(raw_html=unicode(raw_html,"gbk"))
print repr(a.cleaned_text)
```

**Comment by lytk01** [comment]
write dead

**Comment by lytk01** [comment]
中文编码有好几种，改成自动探测会更方便点
`import urllib2
import goose
import chardet
from goose.text import StopWordsChinese

goose_configs = {
    'enable_image_fetching': False,
    'use_meta_language':False,
    'target_language': 'zh',
    'stopwords_class': StopWordsChinese
}

f = urllib2.urlopen("http://tech.hexun.com.tw/2009-06-22/118866465.html")
raw_html = f.read()
chardit1 = chardet.detect(raw_html)
g = goose.Goose(goose_configs)
a = g.extract(raw_html=unicode(raw_html,chardit1['encoding'] ))
print cleaned_text`
