### ISSUE TITLE
Goose fails in extracting articles from The New York Times

### ISSUE THREAD

**Issue by manalsali** [grangier/python-goose#252]
following code:

> import urllib2
> import goose
> url = "http://www.nytimes.com/reuters/2015/12/21/world/africa/21reuters-kenya-attacks-somalia.html?_r=0"
> opener = urllib2.build_opener(urllib2.HTTPCookieProcessor())
> response = opener.open(url)
> raw_html = response.read()
> g = goose.Goose()
> a = g.extract(raw_html=raw_html)
> a.cleaned_text
> u''
> Empty string is returned.

**Comment by robmcdan** [comment]
Your url string looks malformed, but anyway I fixed a similar issue in #225 and pull-requested but I don't think it was ever approved. My fork has this issue fixed and I've been parsing NYtimes happily ever since.

Good luck!

Rob

**Comment by grangier** [comment]
@robmcdan the PR has not been accepted because it breaks the test case suites

**Comment by manalsali** [comment]
@robmcdan @grangier I just bypassed using goose and wrote a little snippet using BeautifulSoup and urllib2 that works.

**Comment by richardpetithory** [comment]
I'm curious; this issue was close because there is a work-around involving some external manipulation?

**Comment by manalsali** [comment]
@richardpetithory No, I closed this issue because @robmcdan has an issue open with this exact same problem [#225](https://github.com/grangier/python-goose/pull/225) so I don't think there is a need for two open requests.
