### ISSUE TITLE
 cannot identify image file

### ISSUE THREAD

**Issue by PriyeshV** [grangier/python-goose#36]
> > > url = "http://manc.it/13L8Jcx"
> > > article = g.extract(url=url)
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/local/lib/python2.7/dist-packages/goose_extractor-1.0.2-py2.7.egg/goose/**init**.py", line 53, in extract
> > >     return self.crawl(cc)
> > >   File "/usr/local/lib/python2.7/dist-packages/goose_extractor-1.0.2-py2.7.egg/goose/**init**.py", line 60, in crawl
> > >     article = crawler.crawl(crawl_candiate)
> > >   File "/usr/local/lib/python2.7/dist-packages/goose_extractor-1.0.2-py2.7.egg/goose/crawler.py", line 98, in crawl
> > >     article.top_image = image_extractor.get_best_image(article.raw_doc, article.top_node)
> > >   File "/usr/local/lib/python2.7/dist-packages/goose_extractor-1.0.2-py2.7.egg/goose/images/extractors.py", line 88, in get_best_image
> > >     image = self.check_large_images(topNode, 0, 0)
> > >   File "/usr/local/lib/python2.7/dist-packages/goose_extractor-1.0.2-py2.7.egg/goose/images/extractors.py", line 120, in check_large_images
> > >     good_images = self.get_image_candidates(node)
> > >   File "/usr/local/lib/python2.7/dist-packages/goose_extractor-1.0.2-py2.7.egg/goose/images/extractors.py", line 264, in get_image_candidates
> > >     good_images = self.get_images_bytesize_match(filtered_images)
> > >   File "/usr/local/lib/python2.7/dist-packages/goose_extractor-1.0.2-py2.7.egg/goose/images/extractors.py", line 280, in get_images_bytesize_match
> > >     local_image = self.get_local_image(src)
> > >   File "/usr/local/lib/python2.7/dist-packages/goose_extractor-1.0.2-py2.7.egg/goose/images/extractors.py", line 343, in get_local_image
> > >     self.link_hash, src, self.config)
> > >   File "/usr/local/lib/python2.7/dist-packages/goose_extractor-1.0.2-py2.7.egg/goose/images/utils.py", line 59, in store_image
> > >     image = self.write_localfile(data, link_hash, src, config)
> > >   File "/usr/local/lib/python2.7/dist-packages/goose_extractor-1.0.2-py2.7.egg/goose/images/utils.py", line 101, in write_localfile
> > >     return self.read_localfile(link_hash, src, config)
> > >   File "/usr/local/lib/python2.7/dist-packages/goose_extractor-1.0.2-py2.7.egg/goose/images/utils.py", line 81, in read_localfile
> > >     image_details = self.get_image_dimensions(identify, local_image_name)
> > >   File "/usr/local/lib/python2.7/dist-packages/goose_extractor-1.0.2-py2.7.egg/goose/images/utils.py", line 36, in get_image_dimensions
> > >     image = Image.open(path)
> > >   File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2008, in open
> > >     raise IOError("cannot identify image file")
> > > IOError: cannot identify image file
> > > g.config.local_storage_path
> > > '/tmp/goose'

**Comment by JoviWZhu** [comment]
Hi grangier, I think this function fetch_images is to update the image relative path, but when I call extract, only fetch in utils\images.py is called, not fetch_images.

Here is my case:

url = "http://www.studytonight.com/mongodb/introduction-to-mongodb"

the error I faced:
MissingSchema: Invalid URL 'images/MongoDB-feature-less-io-operations.png': No schema supplied. Perhaps you meant http://images/MongoDB-feature-less-io-operations.png?

acctually: it is http://www.studytonight.com/mongodb/images/MongoDB-feature-less-io-operations.png.

How can I download the images with extract, or other functions I should call? or para I should set?

Thank you.

Jovi
