### ISSUE TITLE
article.cleaned_text is null

### ISSUE THREAD

**Issue by harikt** [grangier/python-goose#60]
Not getting cleaned_text 

``` python
>>> article = g.extract("http://vocamus.net/dave/?p=1602")
>>> article.cleaned_text
```

**Comment by infinitywings** [comment]
+1 I also encounter the same problem that the extractor just gets the null cleaned_text. The web page is very simple text page. I don't know what happened. Could you please help me solve the problem? @grangier 
`>>> from goose import Goose
>>> g = Goose({'use_meta_language': False, 'target_language':'en'})
>>> content = g.extract(url='https://www.sec.gov/Archives/edgar/data/20/000095012310024631/c97665e10vk.htm')
>>> print content.title
Form 10-K
>>> print content.author
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Article' object has no attribute 'author'
>>> print content.authors
[]
>>> content.cleaned_text
''
>>>`
